### ISSUE TITLE
link to Slack on homepage is incorrect/missing

### ISSUE THREAD

**Issue by justgrimes** [codefordc/codefordc-2.0#110]
The hyperlink to Code for DC Slack is missing....

**Comment by greggish** [comment]
btw I just tried to add someone to slack through the link on the front page, and apparently it worked, but gave me no indication that it did so. Dunno if there's a way to simply say "Great success" ...

**Comment by stvnrlly** [comment]
Good point. I thought that I had put that in, but apparently not. I'll make it happen shortly.
