### ISSUE TITLE
blog posts have double footers

### ISSUE THREAD

**Issue by ajschumacher** [codefordc/codefordc-2.0#116]
e.g., http://codefordc.org/blog/2014/10/30/project-district-housing.html

**Comment by ajschumacher** [comment]
hmm... they still have double footers though? haven't looked into why... did #119 not work?

**Comment by stvnrlly** [comment]
On the site? That would be because it hasn't been pulled into `gh-pages` yet. I figured that will happen when your post goes up.

**Comment by ajschumacher** [comment]
cool deal~
