### ISSUE TITLE
No page to http://codefordc.org/civicjson/specification.html

### ISSUE THREAD

**Issue by noneck** [codefordc/codefordc-2.0#127]

**Comment by stvnrlly** [comment]
We have it as http://codefordc.org/resources/specification.html right now. I've opted for simplified paths, at least until I have more of an idea of how our resources section will develop. It's possible that we already have enough stuff that we could do a `/resources/civicjson/resource` sort of thing, though.

**Comment by noneck** [comment]
then you need to correct your URL on
http://codefordc.org/resources/builder.html

**Comment by stvnrlly** [comment]
Ah, yes! Thanks, it's fixed now.
