### ISSUE TITLE
Add a donate button

### ISSUE THREAD

**Issue by justgrimes** [codefordc/codefordc-2.0#131]
Add a donate button to the Code for DC website; Link: https://secure.codeforamerica.org/page/contribute/default?custom1=Code%20For%20DC

Similar to Code for Boston http://www.codeforboston.org/

**Comment by stvnrlly** [comment]
That sounds good. This button is a link to the CfA page? A button is pretty easy, but are there additional ways that we could highlight it? Perhaps split the page into four sections instead of three: Attend, Discuss, Hack, and Donate?

**Comment by justgrimes** [comment]
I defer; i do want to promote it but not too much; i don't want to come off as screaming for money; also we might want to consider a preamble page that explains that you are giving money to Code for America on our behalf.

**Comment by stvnrlly** [comment]
OK, I'll play around with it. I'm also open to suggestions on the best implementation. It would be really wonderful if CfA could give us a direct form to put on our site.

**Comment by stvnrlly** [comment]
I like the idea of doing a preamble page. Any thoughts about text for it? Here's what I started with:

```
As a brigade of Code for America, Code for DC operates as a 501(c)(3) non-profit organization. Because we are an all-volunteer group, any costs not covered by CfA are paid out-of-pocket. This includes things from hosting fees for apps and services to food for our meetups.

Help support our operations by donating through CfA:

[Button to donation page]
```
