### ISSUE TITLE
Ensure that site is accessible

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/codefordc-2.0#133]
There are a variety of online tools to do this. It may also be worthwhile to have `pa11y` check the website listed in any project on the projects page and include that in the display.

**Comment by justgrimes** [comment]
Excellent suggestion! Might want to consider working with DCPL; they have an accessibility lab and do good work; actually we should make an accessibility checklist for all our projects and recommend to people to test for these things

some suggestions:

ensure everything is html compliant http://validator.w3.org/check?uri=codefordc.org&charset=%28detect+automatically%29&doctype=Inline&group=0

add alt text for images

check the site using WAVE  http://wave.webaim.org/report#/codefordc.org

check colors for colorblindness

check structure/navigation in JAWS (or other screen readers)  http://en.wikipedia.org/wiki/JAWS_%28screen_reader%29

**Comment by stvnrlly** [comment]
This is done. There's also now a dashboard of sites up at accessfordc.herokuapp.com. I also checked out the [HTML CodeSniffer](https://squizlabs.github.io/HTML_CodeSniffer/) for finding all of the elements on the site and it was very useful.
