### ISSUE TITLE
How to submit a blog post

### ISSUE THREAD

**Issue by mattbailey0** [codefordc/codefordc-2.0#94]
We should provide content on how, specifically, to submit a blog post.  This should happen at a minimum on the wiki for the repo or a .md file, but ideally somewhere on the site as well for less technical users.

A few points to keep in mind:
-like, what sort of stuff are you looking for?
-what exactly is the editorial process?  what changes will you make to my post? will you ask my permission first?
-if submitting a pull request, what branch should I submit to and should it go in ../_posts or ../_drafts?
-if submitting non-html, who should I send it to and what do I need besides my text? (headshot dimensions, twitter handle, ...)

**Comment by bschmoker** [comment]
just to point out that there is a dead link to the "how to blog guide" [here](https://github.com/codefordc/codefordc-2.0/blob/master/blog/index.html#L11) 

deferring to how you'd like that to be presented to users, suggest updating the [current guide](https://github.com/codefordc/guides/blob/release/codefordc-blog/make-a-blog-post.md) and linking under [resources page](https://github.com/bschmoker/codefordc-2.0/tree/how-to-blog/_resources) ?

**Comment by stvnrlly** [comment]
Thanks again; looks like this was a remnant of that awkward submodule system.

**Comment by bschmoker** [comment]
rad :smile_cat:
